version: "3.5"

services:
  mongo:
    image: mongo:7.0.5-jammy
    command: mongod --quiet --logpath /dev/null
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: rinha
      MONGO_INITDB_ROOT_PASSWORD: 123
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "400MB"
  api01:
    container_name: api01
    build: .
    command: node index.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    expose:
      - "8080"
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "35MB"
  api02:
    container_name: api02
    build: .
    command: node index.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    expose:
      - "8080"
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "35MB"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "70MB"
networks:
  default:
    driver: bridge
    name: rinha
